name: JRuby CI

on: [push, pull_request]

env:
  JAVA_OPTS: '-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms60M -Xmx1G -XX:InitialCodeCacheSize=40M -XX:ReservedCodeCacheSize=120M'

permissions:
  contents: read

jobs:

  rake-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ['test:jruby:int', 'spec:ruby:fast', 'spec:ji', 'spec:ffi']
        java-version: ['17', '21', '23']
      fail-fast: false

    name: rake ${{ matrix.target }} (Java ${{ matrix.java-version }})

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: List installed Java versions
        run: |
          sudo update-alternatives --list java
          sudo update-alternatives --list javac
          sudo update-alternatives --config java
      - name: Install JDK 17
        run: |
          sudo update-alternatives --set java /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/temurin-17-jdk-amd644/bin/javac

      - name: List installed Java versions
        run: |
          sudo update-alternatives --list java
          sudo update-alternatives --list javac
          sudo update-alternatives --config java
      - name: set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: List installed Java versions
        run: |
          sudo update-alternatives --list java
          sudo update-alternatives --list javac   
          sudo update-alternatives --config java
      # - name: Set alternatives for java and javac
      #   run: |
      #     sudo update-alternatives --set java /usr/lib/jvm/temurin-${{ matrix.java-version }}-jdk-amd64/bin/java
      #     sudo update-alternatives --set javac /usr/lib/jvm/temurin-${{ matrix.java-version }}-jdk-amd64/bin/javac
    
      - name: bootstrap
        run: mvn -Pbootstrap clean package
      - name: bundle install
        run: bin/jruby --dev -S bundle install
      - name: rake ${{ matrix.target }}
        run: bin/jruby -S rake ${{ matrix.target }}

 
